replace printf by fputs where no format is used
Fixes error messages like: src/wiringX.c:72:2: error: format not a string literal and no format arguments [-Werror=format-security] triggered by fprintf(stderr, line);

This is required to build with the Debian distro CFLAGS